language: node_js
node_js:
  - "5.6"
before_script:
  - npm install -g eslint
  - npm install -g eslint-config-airbnb
  - npm install -g eslint-plugin-react
  - npm run lint
  - npm install -g knex
  - psql -c 'create database development;' -U postgres
  - npm run migrate
addons: 
  postgresql: "9.3"
services:
  - postgresql